### ISSUE TITLE
Creation TranslationAtlas class

### ISSUE THREAD

**Issue by EreliaCorp** [EreliaCorp/Sparkle#19]
Allow user to easely localize application using a custom configuration file.
User must be allowed to provide a key, who will return the string corresponding to it.
If no such key exist, the TranslationAtlas must throw an exception.

Custom configuration file:
The configuration file is a list of couple Key / Element, as both strings, and separated by a ":".
Key can't contain a :, but Element can
Element can be on multiples lines, but must be started by a ". If the sentence contain a " " ", it must be prefixed by a "\" to not be detected as end of multiline sentence

Example :
KeyA:TextForKeyA
KeyB:TextWithA:Inside
KeyC:"My custom text
with multipleline"

Interface proposition:
```
class TranslationAtlas
{
private:

public:
    void load(const std::wstring p_path);
    const std::wstring& get(const std::wstring& p_key);
};
```

**Comment by NotCampeur** [comment]
This will inherit or be replace by #17 .
It is then flagged as blocked right now.
